version: '2'
services:
  server:
    build: .
    ports: 
      - 9004:9004
    depends_on: 
      - db
    environment: 
      - DATABASE_URL=postgres://postgres@db:5432/starkloud
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=starkloud