version: "2"
services:
  footerplayer:
    # build: .
    ports: 
      - "9004:9004"
    depends_on: 
      - db
    links: 
      - db
    working_dir: /usr/src/app
    environment: 
      SEQ_DB: starkloud
      SEQ_USER: postgres
      PORT: 9004
      DATABASE_URL: postgres://postgres@db:5432/starkloud
  # web:
  #   image: footerplayer
  #   command: node database/helper.js
  db:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=starkloud